var twitter = "https://twitter.com/joaquinkmenend";
var instagram = "https://www.instagram.com/joaquinkmenendez/";
var github = "https://github.com/joaquinkeonimenendez-ops";

let banner = [];

let aboutme = [
  "<br>",
  `<div id="aboutme-section">`,
  `<span class='underline output-blue'>Who I am</span>`,
  `<pre class="about-body indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm a CS student at UC Irvine. In my spare time I work on AI projects. I've been interested in coding since childhood- fun fact I was awarded my first cash bounty for stored XSS at age 12!</pre>`,
  `<span class="command">What I do</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm currently building Magnum a CLI tool for selling websites to small businesses and Charcoal a web alternative for Obsidian.md out of personal necessity. Use the projects command to explore further.</pre>`,
  "</div>",
];

let social = [
  "<br>",
  'github        <a href="' +
    github +
    '" target="_blank">github.com/joaquinkeonimenendez-ops</a>',
  'instagram     <a href="' +
    instagram +
    '" target="_blank">instagram.com/joaquinkmenendez</a>',
  'twitter       <a href="' +
    twitter +
    '" target="_blank">twitter.com/joaquinkmenend</a>',
  'phone         <a href="tel:+19256832581">+1 925-683-2581</a>',
  'email         <a href="mailto:joaquinkeonimenendez@gmail.com">joaquinkeonimenendez@gmail.com</a>',
];

let help = [
  "<br>",
  `<span class="command">about</span>`,
  "&#8627; Displays who I am.",
  `<span class="command">projects</span>`,
  "&#8627; View coding projects.",
  `<span class="command">contact</span>`,
  "&#8627; Lists contact info.",
];

let projects = [
  "<br>",
  `<div id="projects-section">`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
Charcoal.md - A markdown based note taking webapp inspired by Obsidian. Built for people who can't install desktop apps on work/school devices or don't want to pay for Obsidian sync.
</pre>`,

  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
Magnum - CLI tool for selling websites to small businesses. Scrapes thousands of businesses on google maps that lack websites, researches and generates websites talored to each business, funnels it into a CRM with one click deployment, calls, and Stripe payments. Website templates are recycled so no AI costs are associated with failling to make a sale.
</pre>`,
  "</div>",
];

let thoughts = [
  "<br>",
  `<span class="command">1. Brief thoughts on automation</span>`,
  `<span class="command">Q. Exit thoughts</span>`,
];

let thoughtsAutomation = [
  "<br>",
  `<span class='underline'>Brief thoughts on automation - 1/25/26</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
ai POWERED automation systems are overrated and expensive 
but ai GENERATED automation systems are so fucking overpowered

automation systems usually require SO MUCH upfront cost, effort, and expertise and thats the reason why everything in the world isn't automated (yet). but not anymore

you MUST try generating playwright python scripts WITH opus and the python script does the browser based task not opus itself. 

these scripts are 1000 times more efficient than asking an AI browser to do a task because they're hyper specialized and don't have to relearn every time. and they don't cost any tokens to run. theres just slightly more upfront setup for each task

but there still generated by the brilliance of opus 4.5. you just have to run the script in playwright headed mode and describe to opus 4.5 where it went wrong and to adjust the script accordingly.

also playwright is not like devtools / javascript based interactions. its based on multiple types of selectors rather than simply just elements or classes. slight elemental/class changes to the structure of the webapp you want to automate a task on won't break anything either.

opus + playwright is such a brilliant combo that it can automate tasks before even seeing the website you want to automate it on so long as you describe the UI in your prompt.

gatekeep this tho
</pre>`,
];
