var twitter = "https://twitter.com/joaquinkmenend";
var instagram = "https://www.instagram.com/joaquinkmenendez/";
var github = "https://github.com/joaquinkeonimenendez-ops";

let banner = [];

let aboutme = [
  "<br>",
  `<div id="aboutme-section">`,
  `<span class='underline output-blue'>Who I am</span>`,
  `<pre class="about-body indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm a CS student at UC Irvine. In my spare time I work on AI projects. I've been interested in coding since childhood- fun fact I was awarded my first cash bounty for stored XSS at age 12!</pre>`,
  `<span class="command">What I do</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm currently building Magnum a CLI tool for selling websites to small businesses, and Charcoal a web alternative for Obsidian.md out of personal necessity. Use the projects command to explore further.</pre>`,
  "</div>",
];

let social = [
  "<br>",
  'github        <a href="' +
    github +
    '" target="_blank">github.com/joaquinkeonimenendez-ops</a>',
  'instagram     <a href="' +
    instagram +
    '" target="_blank">instagram.com/joaquinkmenendez</a>',
  'twitter       <a href="' +
    twitter +
    '" target="_blank">twitter.com/joaquinkmenend</a>',
  'phone         <a href="tel:+19256832581">+1 925-683-2581</a>',
  'email         <a href="mailto:joaquinkeonimenendez@gmail.com">joaquinkeonimenendez@gmail.com</a>',
];

let home = [
  "<br>",
  `<span class="cli-run-command cli-run-item" data-run-command="about" data-preview-key="home-option:about"><span class="command">about</span><br><span class="home-item-desc">&#8627; Displays who I am.</span></span>`,
  `<span class="cli-run-command cli-run-item" data-run-command="projects" data-preview-key="home-option:projects"><span class="command">projects</span><br><span class="home-item-desc">&#8627; View coding projects.</span></span>`,
  `<span class="cli-run-command cli-run-item" data-run-command="contact" data-preview-key="home-option:contact"><span class="command">contact</span><br><span class="home-item-desc">&#8627; Lists contact info.</span></span>`,
];

let projects = [
  "<br>",
  `<span class="cli-run-command cli-run-item" data-run-command="charcoal" data-preview-key="project:charcoal"><span class="command">1. Charcoal md</span><br><span class="home-item-desc">&#8627; A markdown note-taking web app inspired by Obsidian.</span></span>`,
  `<span class="cli-run-command cli-run-item" data-run-command="magnum" data-preview-key="project:magnum"><span class="command">2. Magnum</span><br><span class="home-item-desc">&#8627; AI powered CLI for selling websites to small businesses.</span></span>`,
];

let projectCharcoal = [
  "<br>",
  `<span class="output-blue">Charcoal md</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
A markdown-based note-taking web app inspired by Obsidian.
Built for people who can't install desktop apps on work/school devices
or who don't want to pay for Obsidian sync.
</pre>`,
  `<span class="cli-run-command cli-run-item" data-run-command="projects" data-preview-key="project:back"><span class="command">â† Back to projects</span></span>`,
];

let projectMagnum = [
  "<br>",
  `<span class="output-blue">Magnum</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
A CLI for selling websites to small businesses.
Lead generation and website creation are handled by AI agents,
with integrations for OpenPhone and Stripe to support smooth operator workflows.
</pre>`,
  `<span class="cli-run-command cli-run-item" data-run-command="projects" data-preview-key="project:back"><span class="command">â† Back to projects</span></span>`,
];

let thoughts = [
  "<br>",
  `<span class="command">1. Brief thoughts on automation</span>`,
  `<span class="command">Q. Exit thoughts</span>`,
];

let thoughtsAutomation = [
  "<br>",
  `<span class='underline'>Brief thoughts on automation - 1/25/26</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
ai POWERED automation systems are overrated and expensive 
but ai GENERATED automation systems are so fucking overpowered

automation systems usually require SO MUCH upfront cost, effort, and expertise and thats the reason why everything in the world isn't automated (yet). but not anymore

you MUST try generating playwright python scripts WITH opus and the python script does the browser based task not opus itself. 

these scripts are 1000 times more efficient than asking an AI browser to do a task because they're hyper specialized and don't have to relearn every time. and they don't cost any tokens to run. theres just slightly more upfront setup for each task

but there still generated by the brilliance of opus 4.5. you just have to run the script in playwright headed mode and describe to opus 4.5 where it went wrong and to adjust the script accordingly.

also playwright is not like devtools / javascript based interactions. its based on multiple types of selectors rather than simply just elements or classes. slight elemental/class changes to the structure of the webapp you want to automate a task on won't break anything either.

opus + playwright is such a brilliant combo that it can automate tasks before even seeing the website you want to automate it on so long as you describe the UI in your prompt.

gatekeep this tho
</pre>`,
];
