var twitter = "https://twitter.com/joaquinkmenend";
var instagram = "https://www.instagram.com/joaquinkmenendez/";
var github = "https://github.com/joaquinkeonimenendez-ops";

let banner = [];

let aboutme = [
  "<br>",
  `<div id="aboutme-section">`,
  `<span class='underline output-blue'>Who I am</span>`,
  `<pre class="about-body indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm a CS student at UC Irvine. In my spare time I work on AI projects. I've been interested in coding since childhood- fun fact I was awarded my first cash bounty for stored XSS at age 12!</pre>`,
  `<span class="command">What I do</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">I'm currently building Magnum a CLI tool for selling websites to small businesses and Charcoal a web alternative for Obsidian.md out of personal necessity. Use the projects command to explore further.</pre>`,
  "</div>",
];

let social = [
  "<br>",
  'github        <a href="' +
    github +
    '" target="_blank">github.com/joaquinkeonimenendez-ops</a>',
  'instagram     <a href="' +
    instagram +
    '" target="_blank">instagram.com/joaquinkmenendez</a>',
  'twitter       <a href="' +
    twitter +
    '" target="_blank">twitter.com/joaquinkmenend</a>',
  'phone         <a href="tel:+19256832581">+1 925-683-2581</a>',
  'email         <a href="mailto:joaquinkeonimenendez@gmail.com">joaquinkeonimenendez@gmail.com</a>',
];

let help = [
  "<br>",
  `<span class="command">about</span>`,
  "&#8627; Displays who I am.",
  `<span class="command">projects</span>`,
  "&#8627; View coding projects.",
  `<span class="command">thoughts</span>`,
  "&#8627; Read notes and ideas.",
  `<span class="command">contact</span>`,
  "&#8627; Lists contact info.",
];

let projects = [
  "<br>",
  `<div id="projects-section">`,
  `<span class='underline'>Charcoal.md</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
Charcoal.md is a markdown-first note-taking web app inspired by Obsidian: simple, fast, and file-first. Built for people who can't install desktop apps on work/school devices and want a cleaner, faster alternative to Notion.
</pre>`,

  `<span class='underline'>Magnum CLI Tool</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
A semi-autonomous web design agency in your command line: autonomous lead generation, lead prequalification, cost-efficient website generation, all funneled into a CRM for AI-assisted outreach, sales calls, and Stripe payments.
</pre>`,
  "</div>",
];

let thoughts = [
  "<br>",
  `<span class="command">1. Brief thoughts on automation</span>`,
  `<span class="command">Q. Exit thoughts</span>`,
];

let thoughtsAutomation = [
  "<br>",
  `<span class='underline'>Brief thoughts on automation</span>`,
  `<pre class="indent-8 whitespace-pre-wrap break-words overflow-x-auto">
AI powered automation systems are overrated and expensive.
But AI generated automation systems are insanely overpowered.

Automation systems usually require huge upfront cost effort and expertise. That is the reason everything in the world is not automated yet. But not anymore.

You should try generating Playwright Python scripts with Opus where the Python script does the browser task not Opus itself.

These scripts are far more efficient than asking an AI browser to do a task because they are hyper specialized and do not need to relearn each run. They also cost no tokens to execute. There is just a bit more upfront setup per task.

Still they are generated by Opus 4.5. Run the script in Playwright headed mode and tell Opus 4.5 exactly where it failed so it can adjust the script.

Playwright here is text and visual workflow oriented not fragile class selector dependence. Small UI structure changes are less likely to break the workflow.

Opus + Playwright is a brilliant combo. It can automate tasks before seeing the site if your UI description is strong enough.

Gatekeep this though.
</pre>`,
];
